<html>
<head>
<title> LOGIN PAGE </title>
</head>
<body>
    
    <h1><CENTRE><p style="background-color:rgb(175,255,71);"> REGISTER PAGE </p> </CENTRE></h1><BR><HR><BR>

    <form action="logged.php" method="post">
        <label>Enter your email id : </label>
        <input type="text" name="l1"><br><hr>
        <label>Enter your password : </label>
        <input type="text" name="l2"><br><hr>
        <input type="submit" name="ap" value="LOGIN">
        </form>

    <form action="register.php" method="post">
    <p style="color: azure;"><label> INVALID ID OR PASSWORD  </label></p>
    <input type="submit" name="mn" value="REGISTER">
    </form>

</body>
</html>